AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BacketName:
    Type: String
    Default: ot-nemoto.aws-cloudformation-templates

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BacketName
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
          Principal: '*'

Outputs:
  S3BucketSecureURL:
    Value: !Sub https://s3-${AWS::Region}.amazonaws.com/${Bucket}/
