AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ConfigConfigRule:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cloudformation-stack-drift-detection-check
      Description: |
        Checks whether your CloudFormation stacks' actual configuration differs, or has drifted, from its expected configuration.
      InputParameters: !Sub |
        {
          "cloudformationRoleArn": "${IAMRole.Arn}"
        }
      Scope: 
        ComplianceResourceTypes:
        - AWS::CloudFormation::Stack
      Source: 
        Owner: AWS
        SourceIdentifier: CLOUDFORMATION_STACK_DRIFT_DETECTION_CHECK
      MaximumExecutionFrequency: TwentyFour_Hours
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: cloudformation-stack-drift-detection-check-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: config.amazonaws.com
          Action: sts:AssumeRole
      MaxSessionDuration: 3600
      ManagedPolicyArns: 
      - arn:aws:iam::aws:policy/service-role/AWSConfigRole
      - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
  IAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - "iam:Get*"
          Resource: "*"
        - Effect: Allow
          Action:
          - "codestar-connections:Get*"
          - "codestar-connections:List*"
          Resource: "*"
        - Effect: Allow
          Action:
          - "events:Describe*"
          - "events:List*"
          Resource: "*"
        - Effect: Allow
          Action:
          - "lambda:List*"
          - "lambda:Get*"
          Resource: "*"
        - Effect: Allow
          Action:
          - "elasticloadbalancing:Describe*"
          Resource: "*"
      Roles: 
      - !Ref IAMRole
      PolicyName: cloudformation-stack-drift-detection-check-policy

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: aws-config-cloudformation-stack-drift-detection-check
      TopicName: aws-config-cloudformation-stack-drift-detection-check
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument: !Sub |
        {
          "Version": "2008-10-17",
          "Id": "__default_policy_ID",
          "Statement": [
            {
              "Sid": "__default_statement_ID",
              "Effect": "Allow",
              "Principal": {
                "AWS": "*"
              },
              "Action": [
                "SNS:GetTopicAttributes",
                "SNS:SetTopicAttributes",
                "SNS:AddPermission",
                "SNS:RemovePermission",
                "SNS:DeleteTopic",
                "SNS:Subscribe",
                "SNS:ListSubscriptionsByTopic",
                "SNS:Publish",
                "SNS:Receive"
              ],
              "Resource": "${SNSTopic}",
              "Condition": {
                "StringEquals": {
                  "AWS:SourceOwner": "${AWS::AccountId}"
                }
              }
            },
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "events.amazonaws.com"
              },
              "Action": "sns:Publish",
              "Resource": "${SNSTopic}"
            }
          ]
        }
      Topics: 
      - !Ref SNSTopic
  EventsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: aws-config-cloudformation-stack-drift-detection-check
      EventPattern: !Sub |
        {
          "source": ["aws.config"],
          "detail-type": ["Config Rules Compliance Change"],
          "detail": {
            "messageType": ["ComplianceChangeNotification"],
            "configRuleName": ["${ConfigConfigRule}"],
            "newEvaluationResult": {
              "complianceType": ["NON_COMPLIANT"]
            }
          }
        }
      State: "ENABLED"
      Targets: 
      - Arn: !Ref SNSTopic
        Id: 1
        InputTransformer: 
          InputPathsMap: 
            awsAccountId: $.detail.awsAccountId
            awsRegion: $.detail.awsRegion
            compliance: $.detail.newEvaluationResult.complianceType
            resourceId: $.detail.resourceId
            resourceType: $.detail.resourceType
            rule: $.detail.configRuleName
            time: $.detail.newEvaluationResult.resultRecordedTime
          InputTemplate: |
            "On <time> AWS Config rule <rule> evaluated the <resourceType> with Id <resourceId> in the account <awsAccountId> region <awsRegion> as <compliance> For more details open the AWS Config console at https://<awsRegion>.console.aws.amazon.com/config/home?region=<awsRegion>#/resources/timeline?resourceId=<resourceId>&resourceType=<resourceType>"
